src/Core/Web/UAS.Core.Web.WebApp/Controllers/FileManagerController.cs
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;
using UAS.Core.Configuration;

namespace UAS.Core.Web.WebApp.Controllers
{
    public class FileManagerController : SessionController
    {
        /// <summary>
        /// Allows the download of files
        /// </summary>
        /// <param name="filename">Filename to download</param>
        /// <returns>Binary content of the file is this exist</returns>
        public FileResult AsyncDownload(string filename)
        {
            try
            {
                var filepath = Server.MapPath(
                    Path.Combine(
                        ConfigurationManager.AttachmentServerPath, 
                        HttpUtility.HtmlDecode(filename)));

                return File(
                    filepath, MimeMapping.GetMimeMapping(filepath), Path.GetFileName(filename));
            }
            catch (Exception exception)
            {
                return null;
            }
        }
    }
}

src/Core/Web/UAS.Core.Web.WebApp/Controllers/NonAttendanceController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using UAS.Core.DAL.Common.Model;

namespace UAS.Core.Web.WebApp.Controllers
{
    /// <summary>
    /// Manage all the view and actions for the NonAttendance process
    /// </summary>
    public class NonAttendanceController : SessionController
    {
        #region Attributes
        /// <summary>
        /// 
        /// </summary>
        private Facade.Facade _facade;
        #endregion Attributes

        #region Methods
        public NonAttendanceController()
        {
            _facade = new Facade.Facade();
        }

        #region Excuse creator module
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult ExcuseCreator()
        {
            var nonAttendance = GetNonAttendancesPendingForExcuse();
            var classifications = GetExcuseClassifications();
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult PendingExcuseGrid()
        {
            var nonAttendance = GetNonAttendancesPendingForExcuse();
            var classifications = GetExcuseClassifications();
            return PartialView();
        }

        public ActionResult ExcuseCreatorDetail()
        {
            var classifications = GetExcuseClassifications();
            return PartialView(classifications);
        }

        public JsonResult GetNonAttendancePendingForExcuse()
        {
            var userDocumentNumber = base.CurrentSession.SessionUser.DocumentNumber;
            var roleId = base.CurrentSession.SessionUser.IdRole;
            var nonAttendance = _facade.GetNonAttendancePendingForExcuse(userDocumentNumber, roleId);
            return Json(nonAttendance);
        }

        public JsonResult SaveExcuse(Excuse excuse)
        {
            try
            {
                excuse.IdRole = base.CurrentSession.SessionUser.IdRole;
                excuse.DocumentNumber = base.CurrentSession.SessionUser.DocumentNumber;
                _facade.SaveExcuse(excuse);
                return Json(new { Success = true, Message = string.Empty });
            }
            catch (Exception exception)
            {
                return Json(new { Success = false, Message = exception.Message });
            }

        }

        private dynamic GetNonAttendancesPendingForExcuse()
        {
            var userDocumentNumber = base.CurrentSession.SessionUser.DocumentNumber;
            var roleId = base.CurrentSession.SessionUser.IdRole;
            var nonAttendance = _facade.GetNonAttendancePendingForExcuse(userDocumentNumber, roleId);
            ViewBag.NonAttendance = nonAttendance;
            return nonAttendance;
        }

        private dynamic GetExcuseClassifications()
        {
            var roleId = base.CurrentSession.SessionUser.IdRole;
            var classifications = _facade.GetExcuseClassifications(roleId);
            ViewBag.Classifications = classifications;
            return classifications;
        }
        #endregion Excuse creator module

        #region Excuse manager module

        public ActionResult ExcuseManager()
        {
            var excuses = GetExcusesForApproval();
            var status = GetExcuseStatus();
            ViewBag.Status = status;
            ViewBag.Excuses = excuses;
            return View();
        }

        public ActionResult ApprovalExcuseGrid()
        {
            var excuses = GetExcusesForApproval();
            ViewBag.Excuses = excuses;
            return PartialView();
        }

        public ActionResult ApprovalExcuseDetail(int idExcuse)
        {
            var excuses = _facade.GetExcusesForApproval(idExcuse);
            var attachments = _facade.GetAttachments(idExcuse);
            ViewBag.Excuses = excuses;
            ViewBag.Attachments = attachments;
            return PartialView();
        }

        public ActionResult ApprovalExcuse()
        {
            var userDocumentNumber = base.CurrentSession.SessionUser.DocumentNumber;
            var roleId = base.CurrentSession.SessionUser.IdRole;
            var excuses = _facade.GetExcusesForApproval(userDocumentNumber, roleId);
            ViewBag.Excuses = excuses;
            return PartialView();
        }

        public ActionResult ApprovalExcuseStatusChanger()
        {
            var userDocumentNumber = base.CurrentSession.SessionUser.DocumentNumber;
            var roleId = base.CurrentSession.SessionUser.IdRole;
            var status = _facade.GetExcuseStatus(roleId);
            ViewBag.Status = status;
            return PartialView();
        }

        public JsonResult ApproveExcuses(List<ExcuseApprovalView> excuses)
        {
            try
            {
                _facade.ApproveExcuses(excuses);
                return Json(new { Success = true, Message = string.Empty });
            }
            catch (Exception exception)
            {
                return Json(new { Success = false, Message = exception.Message });
            }
        }

        private dynamic GetExcusesForApproval()
        {
            var userDocumentNumber = base.CurrentSession.SessionUser.DocumentNumber;
            var roleId = base.CurrentSession.SessionUser.IdRole;
            var excuses = _facade.GetExcusesForApproval(userDocumentNumber, roleId);
            return excuses;
        }

        private dynamic GetExcuseStatus()
        {
            var roleId = base.CurrentSession.SessionUser.IdRole;
            var status = _facade.GetExcuseStatus(roleId);
            return status;
        }
        #endregion Excuse manager module

        #region Excuse verificator module

        public ActionResult ExcuseVerificator()
        {
            const int DEFAULT_EXCUSE = -1;
            var excuses = GetExcuses();
            var excuseApprovals = _facade.GetExcusesForApproval(DEFAULT_EXCUSE);
            var attachments = _facade.GetAttachments(DEFAULT_EXCUSE);
            ViewBag.ExcuseApprovals = excuseApprovals;
            ViewBag.Attachments = attachments;
            return View(excuses);
        }

        public ActionResult ExcuseVerificatorDetail(int idExcuse)
        {
            var excuseApprovals = _facade.GetExcusesForApproval(idExcuse);
            var attachments = _facade.GetAttachments(idExcuse);
            ViewBag.ExcuseApprovals = excuseApprovals;
            ViewBag.Attachments = attachments;
            return PartialView();
        }

        public ActionResult ExcuseVerificatorGrid()
        {
            var excuses = GetExcuses();
            return PartialView();
        }

        private dynamic GetExcuses()
        {
            var userDocumentNumber = base.CurrentSession.SessionUser.DocumentNumber;
            var roleId = base.CurrentSession.SessionUser.IdRole;
            var excuses = _facade.GetExcuses(userDocumentNumber, roleId);
            ViewBag.Excuses = excuses;
            return excuses;
        }

        #endregion Excuse verificator module
        #endregion Methods
    }
}

src/Core/Web/UAS.Core.Web.WebApp/Views/NonAttendance/ApprovalExcuseDetail.cshtml
@using System.IO;
@using UAS.Core.DAL.Common.Model;

@{
    var excuses = ViewBag.Excuses as IEnumerable<ExcuseApprovalView>;
    var attachments = ViewBag.Attachments as IEnumerable<Attachment>;
}

@functions{
    public static string GetClassification(IEnumerable<ExcuseApprovalView> excuses)
    {
        var excuse = excuses.FirstOrDefault();
        if (excuse != null)
        {
            return excuse.ClassificationExcuse;
        }
        return string.Empty;
    }

    public static string GetJustification(IEnumerable<ExcuseApprovalView> excuses)
    {
        var excuse = excuses.FirstOrDefault();
        if (excuse != null)
        {
            return excuse.ExcuseJustification;
        }
        return string.Empty;
    }

    public static string GetObservation(IEnumerable<ExcuseApprovalView> excuses)
    {
        var excuse = excuses.FirstOrDefault();
        if (excuse != null)
        {
            return excuse.ExcuseObservation;
        }
        return string.Empty;
    }

    public static string DisplayObservation(IEnumerable<ExcuseApprovalView> excuses)
    {
        var excuse = excuses.FirstOrDefault();
        if (excuse != null)
        {
            return string.IsNullOrEmpty(excuse.ExcuseObservation) ? "none" : "block";
        }
        return "none";
    }
}
<div class="modal inmodal" id="modal-approval-excuse" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog  modal-lg">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title text-uppercase">Detalle de la Excusa</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div id="wizard" class="wizard-big">
                        <h1 class="text-uppercase"> General</h1>
                        <fieldset>
                            <div class="row">
                                <div class="col-lg-12">
                                    <form id="form-basic-information">
                                        <div class="form-group">
                                            <label>Clasificación</label>
                                            <input type="text" class="form-control" name="Classification" readonly value="@GetClassification(excuses)" />
                                        </div>
                                        <div class="form-group" style="display: @DisplayObservation(excuses)">
                                            <label>Observación</label>
                                            <textarea class="form-control" rows="5" name="Observation" readonly>@GetObservation(excuses)</textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>Justificación</label>
                                            <textarea class="form-control" rows="10" name="Justification" readonly>@GetJustification(excuses)</textarea>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </fieldset>
                        <h1 class="text-uppercase">Adjuntos</h1>
                        <fieldset>
                            <div class="row">
                                <div class="col-lg-12">
                                    <table id="grid-attachment-excuse" class="table table-striped table-bordered table-hover">
                                        <thead>
                                            <tr>
                                                <th class="center"></th>
                                                <th class="center" style="display: none">Id</th>
                                                <th>Nombre</th>
                                                <th>Fecha</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @if (attachments != null)
                                            {
                                                foreach (var attachment in attachments)
                                                {
                                                    <tr>
                                                        <td>@attachment.Id</td>
                                                        <td style="display: none">@attachment.Id</td>
                                                        <td class="text-uppercase">@Path.GetFileNameWithoutExtension(attachment.Path)</td>
                                                        <td>@attachment.RegisterDate</td>
                                                        <td class="center">
                                                            <a href="@Url.Action("AsyncDownload", "FileManager", new { filename = Html.Encode(Path.GetFileName(attachment.Path)) })" id="@attachment.Id" class="btn btn-sm btn-primary" name="DownloadAttachment" data-toggle="tooltip" data-placement="top" title="Selecciona para descargar el archivo"><span class="fa fa-download"></span></a>
                                                        </td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th class="center"></th>
                                                <th class="center" style="display: none">Id</th>
                                                <th>Nombre</th>
                                                <th>Fecha</th>
                                                <th></th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/Core/Web/UAS.Core.Web.WebApp/Views/NonAttendance/ApprovalExcuseGrid.cshtml
@using UAS.Core.DAL.Common.Model;

@model ExcuseApprovalView

@{
    var excuseCollection = ViewBag.Excuses as IEnumerable<ExcuseApprovalView>;
}
<table id="grid-approval-excuse" class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th class="center"></th>
            <th class="center" style="display: none"></th>
            <th class="center" style="display: none"></th>
            <th class="center" style="display: none"></th>
            <th class="center" style="display: none"></th>
            <th class="center">Curso</th>
            <th># Documento</th>
            <th>Nombre</th>
            <th>Rol</th>
            <th>Fecha</th>
            <th>Horario</th>
            <th>Espacio</th>
            <th>¿Excusa?</th>
            <th class="center"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var excuse in excuseCollection)
        {
            <tr>
                <td><input type="checkbox" class="i-checks" name="input[]"></td>
                <td style="display: none">@excuse.Id</td>
                <td style="display: none">@excuse.IdExcuse</td>
                <td style="display: none">@excuse.IdNonAttendance</td>
                <td style="display: none">@excuse.IdRoleApprover</td>
                <td>@excuse.CourseName</td>
                <td>@excuse.TruantDocumentNumber</td>
                <td>@excuse.TruantFullName</td>
                <td>@excuse.TruantRoleAlias</td>
                <td>@excuse.NonAttendanceDate.ToString("yyyy-MM-dd")</td>
                <td>@{var scheduleDetail = string.Concat(@excuse.StartTime, " - ", @excuse.EndTime); @scheduleDetail}</td>
                <td>@{var spaceDetail = string.Concat(@excuse.SpaceType, " ", excuse.SpaceName); @spaceDetail}</td>
                <td class="center">Si</td>
                <td class="center">
                    <button id="@excuse.IdExcuse" class="btn btn-sm btn-primary" name="ExcuseDetail" data-toggle="tooltip" data-placement="top" title="Selecciona para consultar el detalle"><span class="fa fa-info-circle"></span></button>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th class="center"></th>
            <th class="center" style="display: none"></th>
            <th class="center" style="display: none"></th>
            <th class="center" style="display: none"></th>
            <th class="center" style="display: none"></th>
            <th class="center">Curso</th>
            <th># Documento</th>
            <th>Nombre</th>
            <th>Rol</th>
            <th>Fecha</th>
            <th>Horario</th>
            <th>Espacio</th>
            <th>¿Excusa?</th>
            <th class="center"></th>
        </tr>
    </tfoot>
</table>

src/Core/Web/UAS.Core.Web.WebApp/Views/NonAttendance/ApprovalExcuseStatusChanger.cshtml
@using UAS.Core.DAL.Common.Model;
@{
    var status = ViewBag.Status as IEnumerable<StatusByRoleView>;
    var SEPARATOR = "|";
}
<div class="modal inmodal" id="modal-approval-excuse-status-changer" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title text-uppercase">CAMBIAR ESTADO A</h4>
                <small class="font-bold">Por favor recuerda diligenciar todos los datos requeridos.</small>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <form id="form-basic-information">
                            <div class="form-group">
                                <label>Estado <sup>*</sup></label>
                                <select class="form-control" name="IdStatusApproval">
                                    @if (status != null)
                                    {
                                        foreach (var stat in status)
                                        {
                                            var statValue = string.Concat(@stat.IdStatus, SEPARATOR, @stat.IsLast);
                                            <option value="@statValue">@stat.Status</option>
                                        }
                                    }
                                </select>
                            </div>
                            <div class="form-group" style="display: none">
                                <label>Observación <sup>*</sup></label>
                                <textarea class="form-control" rows="5" name="ObservationApproval"></textarea>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary pull-right" id="btn-update-excuse-status">Actualizar</button>
            </div>
        </div>
    </div>
</div>

src/Core/Web/UAS.Core.Web.WebApp/Views/NonAttendance/ExcuseVerificatorDetail.cshtml
@using System.IO;
@using UAS.Core.DAL.Common.Model;

@{
    var attachments = ViewBag.Attachments as IEnumerable<Attachment>;
    var excuseApprovals = ViewBag.ExcuseApprovals as IEnumerable<ExcuseApprovalView>;
}

@functions{
    public static string GetClassification(ExcuseApprovalView excuse)
    {
        if (excuse != null)
        {
            return excuse.ClassificationExcuse;
        }
        return string.Empty;
    }

    public static string GetJustification(ExcuseApprovalView excuse)
    {
        if (excuse != null)
        {
            return excuse.ExcuseJustification;
        }
        return string.Empty;
    }

    public static string GetObservation(ExcuseApprovalView excuse)
    {
        if (excuse != null)
        {
            return excuse.ExcuseObservation;
        }
        return string.Empty;
    }

    public static string DisplayObservation(ExcuseApprovalView excuse)
    {
        if (excuse != null)
        {
            return string.IsNullOrEmpty(excuse.ExcuseObservation) ? "none" : "block";
        }
        return "none";
    }

    public static string StatusIcon(int statusId)
    {
        if (statusId == 1)
            return "fa fa-clock-o text-warning";

        if (statusId == 2)
            return "fa fa-check-square text-navy";

        if (statusId == 3)
            return "fa fa-times-circle text-danger";

        return "fa fa-exclamation-circle text-success";
    }

    public static string StatusLabel(int statusId)
    {
        if (statusId == 1)
            return "label label-warning";

        if (statusId == 2)
            return "label label-primary";

        if (statusId == 3)
            return "label label-danger";

        return "label label-success";
    }
}
<div class="modal inmodal" id="modal-verificator-excuse" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog  modal-lg">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title text-uppercase">Detalle de la Excusa</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div id="wizard" class="wizard-big">
                        <h1 class="text-uppercase"> General</h1>
                        <fieldset>
                            <div class="row">
                                <div class="col-lg-12">
                                    <form id="form-basic-information">
                                        <div class="form-group">
                                            <label>Clasificación</label>
                                            <input type="text" class="form-control" name="Classification" readonly value="@GetClassification(excuseApprovals.FirstOrDefault())" />
                                        </div>
                                        <div class="form-group" style="display: @DisplayObservation(excuseApprovals.FirstOrDefault())">
                                            <label>Observación</label>
                                            <textarea class="form-control" rows="5" name="Observation" readonly>@GetObservation(excuseApprovals.FirstOrDefault())</textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>Justificación</label>
                                            <textarea class="form-control" rows="10" name="Justification" readonly>@GetJustification(excuseApprovals.FirstOrDefault())</textarea>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </fieldset>
                        <h1 class="text-uppercase">Adjuntos</h1>
                        <fieldset>
                            <div class="row">
                                <div class="col-lg-12">
                                    <table id="grid-attachment-excuse" class="table table-striped table-bordered table-hover">
                                        <thead>
                                            <tr>
                                                <th class="center"></th>
                                                <th class="center" style="display: none">Id</th>
                                                <th>Nombre</th>
                                                <th>Fecha</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @if (attachments != null)
                                            {
                                                foreach (var attachment in attachments)
                                                {
                                                    <tr>
                                                        <td>@attachment.Id</td>
                                                        <td style="display: none">@attachment.Id</td>
                                                        <td class="text-uppercase">@Path.GetFileNameWithoutExtension(attachment.Path)</td>
                                                        <td>@attachment.RegisterDate</td>
                                                        <td class="center">
                                                            <a href="@Url.Action("AsyncDownload", "FileManager", new { filename = Html.Encode(Path.GetFileName(attachment.Path)) })" id="@attachment.Id" class="btn btn-sm btn-primary" name="DownloadAttachment" data-toggle="tooltip" data-placement="top" title="Selecciona para descargar el archivo"><span class="fa fa-download"></span></a>
                                                        </td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th class="center"></th>
                                                <th class="center" style="display: none">Id</th>
                                                <th>Nombre</th>
                                                <th>Fecha</th>
                                                <th></th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </fieldset>
                        <h1 class="text-uppercase">Aprobaciones</h1>
                        <fieldset>
                            <div class="row">
                                <div class="col-lg-12">
                                    <table id="grid-approvals-excuse" class="table table-striped table-bordered table-hover">
                                        <thead>
                                            <tr>
                                                <th></th>
                                                <th># Documento</th>
                                                <th>Nombre</th>
                                                <th>Observación</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @if (excuseApprovals != null)
                                            {
                                                foreach (var approval in excuseApprovals)
                                                {
                                                    <tr>
                                                        <td><i class="@StatusIcon(approval.IdStatusApproval)"></i></td>
                                                        <td class="text-uppercase">@approval.Approver</td>
                                                        <td>@approval.ApproverFullName</td>
                                                        <td>@approval.ExcuseObservation</td>
                                                        <td><span class="@StatusLabel(approval.IdStatusApproval)">@approval.StatusApproval</span></td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th></th>
                                                <th># Documento</th>
                                                <th>Nombre</th>
                                                <th>Observación</th>
                                                <th></th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>